<script setup lang="ts">
import createClient from "openapi-fetch";
import type { paths } from "../../api/openapi" // generated by openapi-typescript
import { useDebuggerStore } from "@/stores/debugger";
import { ref, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import ServiceMap from "@/lib/utils";

const client = createClient<paths>({ baseUrl: "/v2/debugger/" });

const debuggerStore = useDebuggerStore();

// defined props
const props = defineProps<{
  serviceName: string;
  eventType: string;
}>()

// @ts-ignore
const sourceID = ServiceMap[props.serviceName].eventName

const {data,error} =  await client.GET("/events/types", {
      params: {
        query: {
          sourceId: sourceID,
        },
      },
    }); 


const router = useRouter();

const handleEventTypebeClicked = (eventType:any) => {
  router.push(`/${props.serviceName}/${eventType.name}`);
  debuggerStore.selectedEventType = eventType
}    

</script>

<template>
    <!-- <Listbox v-model="debuggerStore.selectedEventType" :options="data?.data" optionLabel="name" class="w-full md:w-14rem" listStyle="max-height:250px"/> -->
    <div class="flex flex-col gap-2 p-2">
      <div
        @click="handleEventTypebeClicked({
          name: 'all',
          description: 'all',
        })"

        :class="{ 
          'p-2 rounded-lg cursor-pointer': true,
          'p-card	 shadow-lg' : props.eventType === `all`,
        }"

      >
        All
      </div>

      <div v-for="eventType in data?.data" @click="handleEventTypebeClicked(eventType)" class="cursor-pointer">
        <div
          :class="{ 
            'p-2 rounded-lg ': true,
            'p-card	 shadow-lg' : props.eventType === eventType.name,
          }"
        >
          {{ eventType.name }}
        </div>
      </div>
   </div>
</template>