<script setup lang="ts">
import createClient from "openapi-fetch";
import type { paths } from "../api/openapi" // generated by openapi-typescript
import Listbox from 'primevue/listbox';
import { useDebuggerStore } from "@/stores/debugger";
import { ref, watch } from "vue";
import { useRoute, useRouter } from "vue-router";

const client = createClient<paths>({ baseUrl: "/v2/debugger/" });

const debuggerStore = useDebuggerStore();

// defined props
const props = defineProps<{
  sourceID: string;
  eventType?: string;
}>()


const {data,error} =  await client.GET("/events/types", {
      params: {
        query: {
          sourceId: props.sourceID,
        },
      },
    }); 


const router = useRouter();


const handleEventTypebeClicked = (eventType:any) => {
  router.push(`/${props.sourceID}/${eventType.any}`);
  debuggerStore.selectedEventType = eventType
}    

</script>

<template>
    <!-- <Listbox v-model="debuggerStore.selectedEventType" :options="data?.data" optionLabel="name" class="w-full md:w-14rem" listStyle="max-height:250px"/> -->
    <div class="flex flex-col gap-2 p-2">
      <div v-for="eventType in data?.data" @click="handleEventTypebeClicked(eventType)" class="cursor-pointer">
        <div
          :class="{ 
            'p-2 rounded-lg ': true,
            'bg-slate-300 shadow-lg' : props.eventType === eventType.name,
          }"
        >
          {{ eventType.name }}
        </div>
      </div>
   </div>
</template>