<script setup lang="ts">
import createClient from "openapi-fetch";
import type { paths } from "../api/openapi" // generated by openapi-typescript
import Listbox from 'primevue/listbox';
import { useDebuggerStore } from "@/stores/debugger";
import { ref, watch } from "vue";
import { useRoute, useRouter } from "vue-router";

const client = createClient<paths>({ baseUrl: "/v2/debugger/" });

const debuggerStore = useDebuggerStore();

// let data = ref([]); // Store the fetched data
// let error; // Store any potential error


// defined props
const props = defineProps<{
  sourceID: string;
  eventType?: string;
}>()


const {data,error} =  await client.GET("/events/types", {
      params: {
        query: {
          sourceId: props.sourceID,
        },
      },
    }); 

// const fetchEventTypes = async () => {
//   try {
//     const response = await client.GET("/events/types", {
//       params: {
//         query: {
//           sourceId: sourceID,
//         },
//       },
//     });
//     data.value = [{name: "all"},...response.data?.data];
//     error = undefined;
//   } catch (err) {
//     console.error("Error fetching event types:", err);
//     error = err;
//   }
// };

// // Fetch data initially or whenever selectedSourceID changes
// watch([sourceID], async () => {
//   console.log("sourceID changed, fetching event types",sourceID);
//   await fetchEventTypes();
// });

const router = useRouter();


const handleEventTypebeClicked = (EventTpye:string) => {
  router.push(`/${props.sourceID}/${EventTpye}`);
}    

</script>

<template>
    <!-- <Listbox v-model="debuggerStore.selectedEventType" :options="data?.data" optionLabel="name" class="w-full md:w-14rem" listStyle="max-height:250px"/> -->
    <div class="flex flex-col gap-2">
      <div v-for="eventType in data?.data" @click="handleEventTypebeClicked(eventType.name)" class="cursor-pointer">
          {{ eventType.name }}
      </div>
   </div>
</template>