<script setup lang="ts">
import createClient from "openapi-fetch";
import type { paths } from "../api/openapi" // generated by openapi-typescript
import Listbox from 'primevue/listbox';
import { useDebuggerStore } from "@/stores/debugger";
import { ref, watch } from "vue";

const client = createClient<paths>({ baseUrl: "/v2/debugger/" });

const debuggerStore = useDebuggerStore();

let data = ref([]); // Store the fetched data
let error; // Store any potential error

const fetchEventTypes = async () => {
  try {
    const response = await client.GET("/events/types", {
      params: {
        query: {
          sourceId: debuggerStore.selectedSourceID,
        },
      },
    });
    data.value = response.data?.data;
    error = undefined;
  } catch (err) {
    console.error("Error fetching event types:", err);
    error = err;
  }
};

// Fetch data initially or whenever selectedSourceID changes
watch(debuggerStore, async () => {
  await fetchEventTypes();
});

</script>

<template>
    <Listbox v-model="debuggerStore.selectedEventType" :options="data" optionLabel="name" class="w-full md:w-14rem" listStyle="max-height:250px"/>
</template>