<script setup lang="ts">
import createClient from "openapi-fetch";
import type { paths } from "../api/openapi" // generated by openapi-typescript
import { useDebuggerStore } from "@/stores/debugger";
import { ref, watch } from "vue";

const client = createClient<paths>({ baseUrl: "/v2/debugger/" });

const debuggerStore = useDebuggerStore();

let eventList = ref([]); // Store the fetched data
let error; // Store any potential error

const fetchEventTypes = async () => {
    try {
        const { data, error } = await client.GET("/events",{
            params: {
                query: {
                    sourceId: debuggerStore.selectedSourceID,
                    eventType: debuggerStore.selectedEventType?.name,
                    offset: 0,
                    length: 100
                }  
            }
        })
        eventList.value = data?.data
    }catch(err){
        console.error("Error fetching event types:", err);
        error = err;
    }
}

watch(debuggerStore, async () => {
    await fetchEventTypes();
});

</script>
<template>
<div>事件历史</div>

<div class="flex flex-col h-96 overflow-scroll rounded-lg gap-2">
    <div v-for="item in eventList">
    <div class="bg-gray-200">{{ item }}</div>
    </div>
</div>
</template>