<script setup lang="ts">
import createClient from "openapi-fetch";
import type { paths } from "../api/openapi" // generated by openapi-typescript
import Listbox from 'primevue/listbox';
import { useDebuggerStore } from "@/stores/debugger";
import { useRouter } from 'vue-router';
import { ref } from "vue";

const client = createClient<paths>({ baseUrl: "/v2/debugger/" });

const { data, error } = await client.GET("/sources")

const beSelectSourceID = ref<string | null>(null);
const router = useRouter();

const handleSourceIDbeClicked = (sourceID:string) => {
    router.push(`/${sourceID}`);
    beSelectSourceID.value = sourceID;
}

</script>

<template>
    <!-- <Listbox v-model="debuggerStore.selectedSourceID" :options="data?.data" class="w-full md:w-14rem" listStyle="max-height:250px"/> -->
     <div class="flex flex-col gap-2 p-2">
        <div v-for="source in data?.data" @click="handleSourceIDbeClicked(source)" class="cursor-pointer">
            <div
                 :class="{ 
                    'p-2 rounded-lg ': true,
                    'bg-slate-300 shadow-lg' : beSelectSourceID === source,
                 }"
            >{{ source }}</div>
        </div>
     </div>
</template>