<script setup lang="ts">
import createClient from "openapi-fetch";
import type { paths } from "../api/openapi" // generated by openapi-typescript
import Listbox from 'primevue/listbox';
import { useDebuggerStore } from "@/stores/debugger";
import { useRouter } from 'vue-router';

const client = createClient<paths>({ baseUrl: "/v2/debugger/" });

const { data, error } = await client.GET("/sources")

const router = useRouter();

const handleSourceIDbeClicked = (sourceID:string) => {
    router.push(`/${sourceID}`);
}
</script>

<template>
    <!-- <Listbox v-model="debuggerStore.selectedSourceID" :options="data?.data" class="w-full md:w-14rem" listStyle="max-height:250px"/> -->
     <div class="flex flex-col gap-2">
        <div v-for="source in data?.data" @click="handleSourceIDbeClicked(source)" class="cursor-pointer">
            {{ source }}
        </div>
     </div>
</template>